<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DigitalSignature.Abstractions\DigitalSignature.Abstractions.csproj" />
    <ProjectReference Include="..\..\src\DigitalSignature.Core\DigitalSignature.Core.csproj" />
    <ProjectReference Include="..\..\src\DigitalSignature.CAdES\DigitalSignature.CAdES.csproj" />
    <ProjectReference Include="..\..\src\DigitalSignature.XAdES\DigitalSignature.XAdES.csproj" />
    <ProjectReference Include="..\..\src\DigitalSignature.JAdES\DigitalSignature.JAdES.csproj" />
    <ProjectReference Include="..\..\src\DigitalSignature.PAdES\DigitalSignature.PAdES.csproj" />
  </ItemGroup>

</Project>
