<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DigitalSignature.Abstractions\DigitalSignature.Abstractions.csproj" />
    <ProjectReference Include="..\DigitalSignature.Core\DigitalSignature.Core.csproj" />
    <ProjectReference Include="..\DigitalSignature.Validation\DigitalSignature.Validation.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="System.Security.Cryptography.Xml" Version="10.0.6" />
  </ItemGroup>
</Project>
